### ISSUE TITLE
Stops responding on opening of research tab

### ISSUE THREAD

**Issue by SilverAmerican** [FluffierThanThou/ResearchTree#10]
Game stops responding on reducing crossings

Here is output log
[RW Output Log.txt](https://github.com/FluffierThanThou/ResearchTree/files/1846289/RW.Output.Log.txt)

**Comment by FluffierThanThou** [comment]
there's a pre-release version over in the releases section that I'd like for you to try. Hopefully it'll fix the issues you're having. If not, please try the debug version in the prior release, and post an output_log generated from that.

Thanks for your help!

**Comment by SilverAmerican** [comment]
The pre release did not fix the issue but I got this lovely debug output log here for ya
[output_log.txt](https://github.com/FluffierThanThou/ResearchTree/files/1849634/output_log.txt)

Thank you!

**Comment by FluffierThanThou** [comment]
ugh. 

Have you got HugsLib? Could you upload an output_log with that? (`Ctrl` + `F12`)

**Comment by SilverAmerican** [comment]
Here is a HugsLib output_log https://gist.github.com/HugsLibRecordKeeper/8d0f96bddcf52df01144b90f82c77b9b
 
Cannot grab log after opening research tab in case that would make a difference. Hitting anything after it gets to reducing crossing results in not responding, log is from main menu

**Comment by FluffierThanThou** [comment]
argh, so many mods! 

I need a reproducible example, but I don't have the time to find all these mods (besides, loading times with that many mods will be long, and not great for quick testing).

If anyone can reproduce this issue with a more manageable set of mods (as few as possible) that would be _very much_ appreciated.

**Comment by FluffierThanThou** [comment]
Should be fixed in the latest pre-release, if you can, please try it and let me know.

**Comment by cheesealmighty** [comment]
Pardon me for opening an old issue, didn't want to open a new one. 

I'm having the same problem after adding few extra mods to my existing playthrough. Here are the logs: 
https://paste.ubuntu.com/p/h3VqY6Gsn9/

Here are the mods that were added last: https://puu.sh/C1E4z/6924e7e0c5.png

I would guess the blueprints mod is causing the issue, seeing that it's the last on the logs, but I'm not sure if the game output logs after or before parsing data. I'll return in a bit after testing without the mod in question.

Edit: Oops. This is already have been documented on their end. Sorry about it. 
> Known compatibility issues with Fluffy Research Tree and Research Pal. Will update ASAP with fix.
