### ISSUE TITLE
Weird Tech Tree Behavior Causing Lag

### ISSUE THREAD

**Issue by SoraHjort** [FluffierThanThou/ResearchTree#13]
I've encountered an odd bug that creates a huge amount of space with no nodes between groups of research nodes. With all this empty space it causes the framerate to drop to 1 frame per every three or so seconds when the Research is open.

The offending mod causing this to rear it's head is the Avali mod https://steamcommunity.com/sharedfiles/filedetails/?id=1314474881

I did give them a small notice of the issue. However I felt like sharing here incase it was something that could be looked into on RT's end, as well as future proofing against this happening.

For size reference here are two comparing images with Avali turned off and on, with it fully zoomed out. Note how much space the scroll bar on the bottom says there is to the right.

https://imgur.com/a/Uq7ZUhS

(Edit: yes those lines just stretch all the way across uninterupted till the right side where they meet nodes.)

If I were to guess just how far it would stretch. At normal zoom, starting from the left side of my monitor, it would stretch all the way to my neighbor's house... across the street.

The Avali mod also causes some odd errors pop up as well when you open the Research Tree. Several items with a lower techlevel than one of it's prerequisites. An item that doesn't appear on it's specified layer. As well a red error within FluffyResearchTree.Tree.Swap

Which can be seen at the end of the output_log.txt here

[output_log.txt](https://github.com/FluffierThanThou/ResearchTree/files/2071617/output_log.txt)

And for the ModsConfig.xml just in case
[ModsConfig.xml](https://github.com/FluffierThanThou/ResearchTree/files/2071593/ModsConfig.txt)

Hope this helps.

**Comment by FluffierThanThou** [comment]
thanks! Sorry it took me so long to reply. 

This issue should be resolved with the latest 0.19 pre-releases, if you can, please try them and let me know.
