### ISSUE TITLE
Broken in unstable release 1980

### ISSUE THREAD

**Issue by SqFKYo** [FluffierThanThou/ResearchTree#15]
Fails to initialize after the newest unstable 1980.

Here's the full log:
https://pastebin.com/TMC93JTh

**Comment by Sixdd6** [comment]
I have a similar issue, "Error while instantiating", log is below
https://git.io/fN9aN

Rimworld 0.19.1987
ResearchTree 2.12.454

**Comment by FluffierThanThou** [comment]
should have been fixed with the latest prereleases
