### ISSUE TITLE
Research Window is Blank

### ISSUE THREAD

**Issue by Sixdd6** [FluffierThanThou/ResearchTree#16]
Using build 2.14.462 on Rimworld build 0.19.1996

When I open the research tab the window is blank, log is below.
https://git.io/fNhZs

**Comment by FluffierThanThou** [comment]
does this still occur on the latest version?

**Comment by notfood** [comment]
Insane how many unrelated errors you have pilled in a single log.

You tried to load a borked save 3 times by the count of:
`Loading game from file Southeastern Alia`

Then for some reason RimWorld tries to apply all the harmony patches again (?), that definitely breaks the hell loose.

RimWorld was already in a dubious state, It seems you tried opening the Research tab after all that mess, Research Tree builds the tree on first open and with the strange state it erroed even more and showed you a black screen.

I suggest you should produce a cleaner log, something we can reproduce on our side.
