### ISSUE TITLE
Autocannon Turret Incorrect Research Icon

### ISSUE THREAD

**Issue by DerpyMoa** [FluffierThanThou/ResearchTree#21]
Hello, 
This particular Research lists that it unlocks Uranium Slug Turret but it doesn't.
The Research after it does.
This is without any other mods.

Screen: https://i.imgur.com/6qnZjgd.png

**Comment by FluffierThanThou** [comment]
Actually, technically, they do depend on both researches, so the icons are correct :P.

That said, such sloppiness in the defs should not be tolerated, so I've added some logic to filter out research prerequisites that are pointless.
