### ISSUE TITLE
low fps?

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/ResearchTree#6]

**Comment by FluffierThanThou** [comment]
partially bug related (need to reevaluate the bad research config resolvers), and partially just a fact of life with rendering soooo many textures. 

Implementing #3 and #4 is going to make this even worse...

**Comment by MitztheKat** [comment]
make this high priority. i have an error that i am able to copy plus hugslib logs.
the main debug log is here and is the last error. https://git.io/vxRTH
it's just... laggy.
and then there's the last error. try throwing a few of my mods in you haven't tested yet and could contribute to lag..

**Comment by FluffierThanThou** [comment]
looks like a bad research configuration in one of your mods, but your modlist is so huge it's going to be hard for me to figure out which one. 

Could you please manually install the debug version (see the latest release), and post a log from that? The error won't be fixed, but there should be a lot more information in the log.

**Comment by MitztheKat** [comment]
sure! i will get right to that!
it might take a while to boot up my gaming rig and reinstall the mod.

**Comment by FluffierThanThou** [comment]
I've also had a look at a possible cause of your problems, there's a pre-release version on github I'd like for you to try. I haven't got the 'bad' mods to test it myself, so any feedback on that would be much appreciated.

**Comment by MitztheKat** [comment]
got the log for it.
https://git.io/vxumq
so far, i saw lag starting at "reducing crossing" or something about crossing.
the research tab zooms in and out.
an average of 1-3 FPS when in research tab, loaded.

**Comment by FluffierThanThou** [comment]
Are you sure that's the debug version? 

Could you also try this version; https://github.com/FluffierThanThou/ResearchTree/releases/download/v0.18.0.8/Research.Tree.zip
?

**Comment by MitztheKat** [comment]
dear, i just noticed the newest release said the exact same things. i'll get a different release

**Comment by FluffierThanThou** [comment]
the log you posted was from the 0.18.0.7 release, that wasn't expected to fix anything, and doesn't contain the debug information. Kindly try the 0.18.0.8 pre-release, and if that doesn't work post a log from the 0.18.0.7 release, DEBUG version.

**Comment by MitztheKat** [comment]
i got the debug version first, i now know. https://pastebin.com/uyUxN54w has the log messages from loading the save.

**Comment by MitztheKat** [comment]
i just noticed.
please explain the "DUMMY" spam ;-;

**Comment by FluffierThanThou** [comment]
That's the problem ;) 

Say if a research X is connected to Y, but Y is several nodes to the right. 
```
X---Y
```
The horizontal position of a node is it's 'layer', so X is on layer 1, Y on layer 5. The dummies (`-`) are created to link X and Y, so in this case three dummies are created.

The layers are calculated based on two rules;
 - research prerequisites (if Y depends on X, the layer of Y is always higher than X)
 - tech levels (all research on techlevel 'Spacer' is always on a higer layer than any research on techlevel 'Industrial').

The problem arises because some modded research has a weird techlevel and prerequisite chain, e.g. an 'Industrial' level research has a 'Spacer' level research as a prerequisite. The above two rules conflict, and a large number of extra empty layers is created. That in turn means a lot of extra dummy nodes are created, and that in turn means a lot of extra drawing/computations.

I try to catch and 'fix' such weird dependency chains, but clearly I'm not catching all of them (at least not in version 0.18.0.7 and earlier). Version 0.18.0.8 (the pre-release one) should hopefully catch all these dependency chains, and fix the problem.

**Comment by FluffierThanThou** [comment]
Could you tell me what mod(s) PrecisionTurret, BlastTurret, VulcanCannon and GunTurrets are from?

**Comment by FluffierThanThou** [comment]
I figured out what mod they're from (More Vanilla Turrets [B18], http://steamcommunity.com/sharedfiles/filedetails/?id=1206853119&searchtext=turrets), and they are indeed badly configured (the projects are _industrial_ but depend on `Charged Shot`, which is _Spacer_ tech.

It seems to work fine with the 0.18.0.8 version though, but I don't have all of the other mods you've got loaded, so I can't be certain this fixes everything. Please confirm it for me ;)

**Comment by MitztheKat** [comment]
i'm back on my gaming rig, i was out for a bit, gonna test this new update!

**Comment by MitztheKat** [comment]
found incompatibilities - more vanilla turrets
as soon as i remove it it's fine. even mid-game
