### ISSUE TITLE
Research items stacked on top of each other.

### ISSUE THREAD

**Issue by airtonix** [FluffierThanThou/ResearchTree#8]
Preventing me from clicking the one I want.

![download](https://user-images.githubusercontent.com/61225/34968766-1ae6e984-fabb-11e7-81f7-3e9a7b0de0a6.jpg)

**Comment by FluffierThanThou** [comment]
I'm pretty sure this is the Research _Pal_ mod, not my Research _Tree_. (Yes they look basically the same).
